# Generated by Django 5.1 on 2025-10-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay'), ('INSTALLMENTS', 'Installments'), ('COD', 'Cash on Delivery'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='name',
            field=models.CharField(choices=[('TABBY', 'Tabby'), ('TAMARA', 'Tamara'), ('ZIINA', 'Ziina')], max_length=50, unique=True),
        ),
    ]
