# Generated by Django 5.1 on 2025-10-29 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_productvariantoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/usecase/')),
                ('usecase_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('DESSERT', 'Dessert'), ('GIFT', 'Gift'), ('COOKING', 'Cooking'), ('SNACK', 'Snack'), ('CELEBRATION', 'Celebration'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(help_text='Short title for this use case', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of how product is used')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usecase_images', to='products.product')),
            ],
            options={
                'db_table': 'product_usecase_images',
                'ordering': ['display_order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('display_order__gte', 1), ('display_order__lte', 4)), name='usecase_display_order_range')],
            },
        ),
    ]
