# Generated by Django 5.1 on 2025-10-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimageusecase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimageusecase',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='productimageusecase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productimageusecase',
            name='title',
        ),
        migrations.RemoveField(
            model_name='productimageusecase',
            name='usecase_type',
        ),
        migrations.AlterField(
            model_name='productimageusecase',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order 1-4'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 1), ('display_order__lte', 3)), name='base_image_display_order_range'),
        ),
    ]
